# Basic setup
name = "workerlogstodiscord"
main = "worker.js"
compatibility_date = "2025-01-17"
preview_urls = false
send_metrics = false
workers_dev = false

[vars]
SERVICE_NAME = "Cloudflare Logger"
